name: todoey
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0

  cupertino_icons: ^1.0.8

  retrofit: ^4.6.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.5
  retrofit_generator: ^9.6.0
  build_runner: ^2.5.4

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ksa.avif
    - assets/images/Rosh-Hashanah.webp
